### ISSUE TITLE
你好我正在学习你的项目并写一个wanandroid项目但是现在遇到个问题

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [SamiuZhong/WanAndroid_Gank#2]
看了你的登入布局，Textinputlayout 的形状是怎么改变的的我查看了style的代码并没有引入shape里的资源，现在很纠结，请问你是怎么引入的。大佬？

**Comment by SamiuZhong** [comment]
你好，这个形状的确是通过style文件来实现的。
这里对应的style的parent是"Widget.MaterialComponents.TextInputLayout.OutlinedBox"，这个OutlineBox是Material Design包里面封装好专门用来绘制TextInputLayout形状的，更底层的细节可以往上追溯源码。

另外，当前分支的代码有一点影响使用的问题，是因为我正在做Paging3的调试。
已经提交了最新的代码，可以更新看看。
